name: Action Practice

on:
  push

env:
  TZ: Asia/Shanghai

jobs:
  # a single job
  py-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install requirements
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r ./requirements.txt
      - name: Run
        run: |
          python3 ./py_action.py img output
          rm -rf ./css
          rm -rf ./js
          rm -rf ./img
          mv output/* ./
      - name: Commit
        env:
          GIT_NAME: GitHub Actions[Bot]
          GIT_EMAIL: github-actions[bot]@users.noreply.github.com
          # GIT_NAME: ${{ secrets.GIT_NAME }}
          # GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        run: |
          git config --local user.name $GIT_NAME
          git config --local user.email $GIT_EMAIL
          git add .
          git commit -m "Github action update at `date '+%Y-%m-%d %H:%M:%S'`."
      - name: Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master

